@BASE_URL= http://localhost:3000/api


### Bad route
GET {{BASE_URL}}

### Retreives all tasks
GET {{BASE_URL}}/tasks

### Retreives all tasks
GET {{BASE_URL}}/tasks?page=2&limit=4&search=d&sort[title]=title&sort[asc]=asc


### Retreives a single task
@taskId = 56
GET {{BASE_URL}}/tasks/{{taskId}}

### Delete a task
DELETE {{BASE_URL}}/tasks/{{taskId}}

### Create a task
POST {{BASE_URL}}/tasks
content-type: application/json

{
  "title":"abc",
  "description":"La description",
  "start_date": "2023-06-01T00:00:00.000Z",
  "end_date": "2023-06-30T00:00:00.000Z",
  "user_id":1
}

### Update a task
PATCH http://localhost:3000/api/tasks/22
Content-Type: application/json

{
  "title": "Tâche mise à jour 2",
  "description": "Description mise à jour de la tâche",
  "user_id": 1,
  "status": "in_progress",
  "maman":"sdfsdfds",
  "papy":34
}
